name: Quality Checks
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  contents: read
  id-token: write
  packages: write
  actions: read

jobs:

  quality-tests:
    uses: POC-Vish/github-actions/.github/workflows/quality-checks.yml@v0.0.2
    secrets: inherit
