name: Quality Checks
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  contents: read
  id-token: write
  packages: write
  actions: read

jobs:

  quality-tests:
    uses: mclm-dps/reusable-workflow-nodejs-quality-checks/.github/workflows/codeql-analysis.yml@ghas-demo
    secrets: inherit
